"""added cart items column + adding them behavior

Revision ID: 0a8fa8978ed8
Revises: 3850fa9f123d
Create Date: 2025-09-03 10:20:35.919558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8fa8978ed8'
down_revision = '3850fa9f123d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cartItems', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cartItems')

    # ### end Alembic commands ###
